name: HTB to Notion Sync

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  sync_htb_notion:
    runs-on: ubuntu-latest

    steps:
    - name: 🛎️ Checkout du repo
      uses: actions/checkout@v4

    - name: 🐍 Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Installer les dépendances
      run: pip install requests notion-client

    - name: 🔐 Exécuter le script Python
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID_MACHINES: ${{ secrets.DATABASE_ID_MACHINES }}
        DATABASE_ID_MODULES: ${{ secrets.DATABASE_ID_MODULES }}
        HTB_USERNAME: ${{ secrets.HTB_USERNAME }}
        HTB_EMAIL: ${{ secrets.HTB_EMAIL }}
        HTB_PASSWORD: ${{ secrets.HTB_PASSWORD }}
      run: python htb_to_notion.py
